services:
  - type: web
    name: lost-and-found
    env: python
    buildCommand: |
      # ADD THIS LINE to install the GDAL system library
      apt-get update && apt-get install -y libgdal-dev
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "gunicorn lostandfound.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lost-and-found-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: lost-and-found-db
    databaseName: lostandfound
    user: lostandfound_user
    plan: free
    extensions:
      - enabled: postgis