services:
  - type: web
    name: lost-and-found
    env: python
    buildCommand: |
      apt-get update && apt-get install -y binutils libproj-dev gdal-bin
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn lostandfound.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lostandfound-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: lostandfound-db
    databaseName: lostandfound
    user: lostandfound_user
