# Generated by Django 5.2.4 on 2025-07-31 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=10)),
                ('item_type', models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Apparel', 'Apparel'), ('Other', 'Other')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='item_photos/')),
                ('contact_info', models.CharField(help_text='Email or phone number for contact', max_length=200)),
                ('lost_date', models.DateField()),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
