# Generated by Django 5.2.4 on 2025-08-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='secret_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='secret_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
