# Generated by Django 5.2.4 on 2025-08-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_notification_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
