# Generated by Django 5.2.4 on 2025-08-04 06:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
