# Generated by Django 5.2.4 on 2025-08-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_item_location_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location_point',
        ),
    ]
